pipeline {
    agent any
	stages {
	stage ('checkout scm') {
			steps {
				checkout scm
			}
		}
        stage('Build') {
            steps {
               sh 'mvn -f backend/pom.xml clean install'
            }
        }
	}
}
