pipeline {
    agent any
	stages {
	stage ('checkout scm') {
			steps {
				checkout scm
			}
		}
        stage('Build') {
            steps {
		    sh 'cd backend'
               sh 'mvn clean install'
            }
        }
	}
}
