pipeline {
    agent any
    
		stage ('checkout scm') {
			steps {
				checkout scm
			}
		}
        stage('Build') {
            steps {
                mvn clean install
            }
        }
    }
}
